# Generated by Django 5.0.1 on 2024-02-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('percentage', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
